=== julien-noblet/geepro/trunk/geepro/drivers/drivers.dtd
<!ENTITY % position
    'expand  (true|false) "false"
    fill     (true|false) "false"
    box_end  (true|false) "false"
    border   CDATA #IMPLIED
    expandx  (true|false) "false"
    expandy  (true|false) "false"
    fillx    (true|false) "false"
    filly    (true|false) "false"
    spacex   CDATA #IMPLIED
    spacey   CDATA #IMPLIED
    pos      CDATA #IMPLIED'
>

<!ELEMENT gui (info, notebook?)>
<!ELEMENT info ANY>
<!ELEMENT notebook ANY>

<!ELEMENT if (frame?, description?, image?, dipswitch?, jumper?, hbox?, vbox?, table?)>
<!ELEMENT frame ANY>
<!ELEMENT table ANY>
<!ELEMENT dipswitch EMPTY>
<!ELEMENT jumper EMPTY>
<!ELEMENT image EMPTY>
<!ELEMENT description (#PCDATA)>
<!ELEMENT button EMPTY>
<!ELEMENT chbutton EMPTY>
<!ELEMENT spinbutton EMPTY>
<!ELEMENT entry EMPTY>
<!ELEMENT hbox ANY>
<!ELEMENT vbox ANY>


<!ATTLIST notebook name CDATA #REQUIRED>
<!ATTLIST if chip ID #REQUIRED>
<!ATTLIST frame 
    label CDATA #IMPLIED
    align CDATA #IMPLIED
    shadow (in|out|etched_in|etched_out|none) "in"
    %position;
>
<!ATTLIST table dim CDATA #REQUIRED>
<!ATTLIST dipswitch 
    name CDATA	#IMPLIED
    len  CDATA  #REQUIRED
    value CDATA #REQUIRED
    %position;
>
<!ATTLIST jumper 
    set (0 | 1) "0"
    name_up CDATA #IMPLIED
    name_dn CDATA #IMPLIED
    %position;
>
<!ATTLIST button 
    id ID #REQUIRED
    label CDATA #REQUIRED
    %position;
>
<!ATTLIST chbutton 
    id ID #REQUIRED
    sensitive (0 | 1) "1"
    lab (right|left) "left"
    label CDATA #REQUIRED
    %position;
>
<!ATTLIST spinbutton 
    id ID #REQUIRED
    type (hex | dec) "dec"
    max CDATA #REQUIRED
    label CDATA #REQUIRED
    %position;
>
<!ATTLIST entry 
    id ID #REQUIRED
    editable (0 | 1) "1"
    %position;
>
<!ATTLIST image 
    src CDATA #REQUIRED
    %position;
>


<!ATTLIST hbox
    %position;
    spacing CDATA #IMPLIED
>

<!ATTLIST vbox
    spacing CDATA #IMPLIED
    %position;
>

=== julien-noblet/geepro/geepro/drivers/memsim.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/css" href="drivers.css" ?>
<!DOCTYPE gui SYSTEM "drivers.dtd">

<gui>

<info>
    <frame align="50, 50" >
	<vbox>
	    <description>8/16 bit EPROM simulator</description>
	    <image src="pixmaps/memsim.jpg"/>
	</vbox>
    </frame>
</info>

<notebook name="HW Test">
    <table dim="2,2">
	<frame  shadow="etched_in" expand="true" fillx="true" pos="0,1, 0,1">
	    <table dim="5, 3" fillx="true">
		<chbutton id="READY" pos="0,2, 0,1" label="LED - READY" fillx="true" spacex="5" />
		<chbutton id="TRANS" pos="0,2, 1,2" label="LED - TRANSMISSION" fillx="true" spacex="5" />
		<chbutton id="RST_ST" pos="0,2, 2,3" label="RESET STATE" fillx="true" spacex="5" spacey="5" />		
		<chbutton id="RST_OUT" pos="0,2, 3,4" label="RESET OUT" fillx="true" spacex="5" spacey="5" />		
	    </table>	    
	</frame>
	<image src="pixmaps/memsim_lpt_sch.png" pos="0,2, 1,2"/>
    </table>
</notebook>

</gui>

=== julien-noblet/geepro/trunk/geepro/drivers/willem.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/css" href="drivers.css" ?>
<!DOCTYPE gui SYSTEM "drivers.dtd">

<gui>

<info>
    <frame label="Programmer settings">
	<vbox>
	    <if chip="none">
		<description>Simple popular programmer.</description>
		<image src="./pixmaps/mcs48.png"/>
		<vbox>
		    <hbox border="0">
			<jumper name_up="29x" set="1"/>
			<dipswitch name="Dip switch" len="12" value="0x00000"/>
		    </hbox>
		</vbox>
	    </if>
	</vbox>
    </frame>
</info>

<notebook name="HW Test">
    <table dim="2,3">
	<frame label="ZIF32" pos="0,1, 0,3" align="0,0">
	    <hbox>
		<frame shadow="in">
		    <vbox>
			<chbutton id="pin_1" label="1-Vpp" />
			<chbutton id="pin_2" label="2-A16" />
			<chbutton id="pin_3" label="3-A15" />
			<chbutton id="pin_4" label="4-A12" />
			<chbutton id="pin_5" label="5-A7"  />
			<chbutton id="pin_6" label="6-A6"  />
			<chbutton id="pin_7" label="7-A5"  />
			<chbutton id="pin_8" label="8-A4"  />
			<chbutton id="pin_9" label="9-A3"  />
			<chbutton id="pin_10" label="10-A2"/>
			<chbutton id="pin_11" label="11-A1"/>
			<chbutton id="pin_12" label="12-A0"/>
			<chbutton id="pin_13" label="13-D0"/>
			<chbutton id="pin_14" label="14-D1"/>
			<chbutton id="pin_15" label="15-D2"/>
			<chbutton id="pin_16" sensitive="0" label="16-GND"/>
		    </vbox>    
		</frame>
		<frame shadow="in">
		    <vbox>
			<chbutton id="pin_32" lab="right" label="Vcc-32"/>
			<chbutton id="pin_31" lab="right" label="WE-31" />
			<chbutton id="pin_30" lab="right" label="A17-30"/>
			<chbutton id="pin_29" lab="right" label="A14-29"/>
			<chbutton id="pin_28" lab="right" label="A13-28"/>
			<chbutton id="pin_27" lab="right" label="A8-27" />
			<chbutton id="pin_26" lab="right" label="A9-26" />
			<chbutton id="pin_25" lab="right" label="A11-25"/>
			<chbutton id="pin_24" lab="right" label="OE-24" />
			<chbutton id="pin_23" lab="right" label="A10-23"/>
			<chbutton id="pin_22" lab="right" label="CE-22" />
			<chbutton id="pin_21" lab="right" label="D7-21" />
			<chbutton id="pin_20" lab="right" label="D6-20" />
			<chbutton id="pin_19" lab="right" label="D5-19" />
			<chbutton id="pin_18" lab="right" label="D4-18" />
			<chbutton id="pin_17" lab="right" label="D3-17" />
		    </vbox>
		</frame>
	    </hbox>
	</frame>
	<frame label="Set Address/Data" pos="1,2, 0,1">
	    <vbox>
		<spinbutton id="address" type="hex" max="0xffffff" label="Address:"/>
		<spinbutton id="data" type="hex" max="0xff" label="Data:"/>
		<button id="rd_data_bt" label="Read data D0..D7"/>
	    </vbox>
	</frame>
	<frame label="Pamiec 93Cxx" pos="1,2, 1,2">
	    <table dim="2,4">
		<chbutton id="pin_cs" pos="0,1, 0,1" label="1-CS" />
		<chbutton id="pin_clk" pos="0,1, 1,2" label="2-CLK" />
		<chbutton id="pin_di" pos="0,1, 2,3" label="1-DI" />
		<entry id="pin_do_et" editable="0" pos="0,1, 3,4" />
		<button id="clk_sqw" pos="1,2, 1,2" label="CLK SQW" />
		<button id="pin_do_bt" pos="1,2, 3,4" label="4-DO" />
	    </table>	
	</frame>
	<dipswitch name="Dip switch" len="12" value="0xaaaaa" pos="1,2, 2,3" />
    </table>
</notebook>

</gui>
